language: R
cran: https://cran.rstudio.com
cache:                        
  packages: true                # optional
  directories: _bookdown_files  # optional
pandoc_version: 2.3.1

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: pages
    target_branch: gh-pages
    local_dir: _book
    skip_cleanup: true
    github-token: $GITHUB_PAT    # Set in the settings page 
    on:
      branch: master
  - provider: pages
    target_branch: book_draft
    local_dir: _book
    skip_cleanup: true
    github-token: $GITHUB_PAT    # Set in the settings page 
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
      